microsoft/mfcmapi

NamedPropCache.cpp
NamedPropCache.h
StdAfx.h

Plus get rid of new/delete of NamedPropCacheEntry.
You don't have to take this if you don't want :) - just thought I send you your first pull request.

Update named prop cache to use stl algorithm find_if

---

.gitignore
IO/File.cpp
Interpret/String.cpp
Interpret/String.h
MAPI/MAPIProcessor/DumpStore.cpp
MAPI/MAPIProcessor/MapiProcessor.cpp
MFCMapi.sln
UnitTest/UnitTest.vcxproj
UnitTest/UnitTest.vcxproj.filters
UnitTest/stdafx.cpp
UnitTest/stdafx.h
UnitTest/stringtest.cpp
UnitTest/targetver.h

Mostly complete testing for strings.cpp

Add unit testing to MFCMAPI/MrMAPI

---

IO/Registry.cpp
Interpret/SmartView/SmartView.cpp
Interpret/String.cpp
MAPI/NamedPropCache.cpp
MAPI/StubUtils.cpp
MrMapi/MMSmartView.cpp
UI/Controls/SingleMAPIPropListCtrl.cpp
UI/MyMAPIFormViewer.cpp
UI/MyWinApp.cpp
UI/UIFunctions.cpp
UI/ViewPane/CheckPane.cpp
UI/ViewPane/CountedTextPane.cpp
UI/ViewPane/DropDownPane.cpp
UI/ViewPane/ListPane.cpp
UI/ViewPane/SmartViewPane.cpp
UI/ViewPane/TextPane.cpp

Merging @ip-gpu changes to one request

Merging std::nothrow changes from ip-gpu

---

appveyor.yml

Remove symbols from release

---

appveyor.yml

Removed them from the artifacts instead of the deployment. Added back to artifacts and altered deployment filter

Removal of Symbols Too Harsh

---

IO/MFCOutput.cpp
IO/MFCOutput.h
Interpret/Sid.cpp
Interpret/SmartView/SDBin.cpp
MrMapi/MMPst.cpp
MrMapi/MMSmartView.cpp
MrMapi/MrMAPI.vcxproj

Mrmapi input

---

IO/Error.h

Properly hide dialog on cancel in EC_H_CANCEL

---

UI/Dialogs/Editors/Editor.cpp

Constrain our DeferWindowPos logic to just the panes and let the other controls just use SetWindowPos.
Fixes #217

Fix DeferWindowPos 

---

UI/FakeSplitter.cpp
UI/ViewPane/SplitterPane.h

found a leak, and esc acts wierd

Splitter fixes

---

UI/UIFunctions.cpp
UI/ViewPane/TextPane.cpp
UI/ViewPane/TextPane.h

Can handle highlighting multiple ranges, clear

Highlight routine

---

UI/Dialogs/AboutDlg.cpp
UI/Dialogs/BaseDialog.cpp
UI/Dialogs/Dialog.cpp
UI/Dialogs/Dialog.h
UI/Dialogs/Editors/Editor.cpp
UI/UIFunctions.cpp

Fix unicode handling of window titles

---

UI/Dialogs/ContentsTable/AbDlg.cpp
UI/ViewPane/CountedTextPane.cpp
UI/ViewPane/TextPane.cpp

Shrink collapsed edit boxes so they can't steal focus

---

MrMapi/MMPst.cpp

Handle PST output better when file is locked or not found. Protect against div/0.

MrMAPI PST Tweaks

---

UI/ViewPane/SmartViewPane.cpp
core/smartview/EntryIdStruct.cpp
core/smartview/SmartViewParser.cpp
core/smartview/block/block.h

Fix for highlighting the contab entry id.

Fixed issue 318 - contab highlight

---

UI/Controls/SortList/SingleMAPIPropListCtrl.cpp
UI/Controls/SortList/SingleMAPIPropListCtrl.h
core/propertyBag/mapiPropPropertyBag.h
core/propertyBag/rowPropertyBag.h

Prop Bags Null After Dialog

---

MrMapi/MMErr.cpp
MrMapi/MMFolder.cpp
MrMapi/MMMapiMime.cpp
MrMapi/MMProfile.cpp
MrMapi/MMPropTag.cpp
MrMapi/MMPst.cpp
MrMapi/MMReceiveFolder.cpp
MrMapi/MMSmartView.cpp
MrMapi/MrMAPI.cpp
MrMapi/mmcli.cpp
core/mapi/cache/namedProps.cpp
core/mapi/mapiOutput.cpp

properly accept unicode command line parameters and display unicode output

Unicode Command Line Interface Updates

---

UnitTest/tests/stringtest.cpp
core/utility/strings.cpp

Base 64 Reject invalid input

---

core/mapi/processor/mapiProcessor.cpp

Was only checking first attachment instead of each individually

Embedded Messages Not Exporting

---

docs/Documentation.md
docs/MFCMAPIArticles.md

Some have new homes. Others can be rescued from the Wayback Machine. And still others are gone forever.

Fixing various broken links

---

UI/Controls/SortList/SingleMAPIPropListCtrl.cpp
core/propertyBag/mapiPropPropertyBag.cpp

Fix AV
Fix MAPI_E_NOT_FOUND should show on requested missing props

PropBag issues

---

UI/Dialogs/ContentsTable/FolderDlg.cpp
UI/Dialogs/propList/SingleMessageDialog.cpp
UI/file/FileDialogEx.cpp

ensure new dialog on import
avoid error dialog on cancels
clean up file code a bit
Fix #464

Import improvements

---

UI/Dialogs/Editors/propeditor/PropertyEditor.cpp
core/smartview/SmartView.h

Also Toggle smartview on input type
Fixes #525

Check prop type before getting bin
